### Model History & Purpose

The probability of default ("PD") model developed by Company ABC was developed to meet the 2016 CECL standard regulatory requirement for a more *forward-looking* estimation of credit losses by financial institutions in the United States.

### Overall Conclusions

The PD model developed by Company ABC appears to be statistically robust, conceptually sound, and correctly implemented. The validation team independently replicated the PD model development processes in the code repository associated with this report.

### Observations and Recommendations

The validation team rated the following observations and recommendations on a three-tier scale in terms of risk posed to Company ABC:

- **High** risk
- **Moderate** risk
- **Low** risk

1. [Remediate Incorrect Sign for Coefficient](#sec-model-reperformance):
    + **Category**: Model Parameters
    + **Rating**: **Moderate**
    + **Recommendation**: It appears that the model documentation incorrectly displays the coefficient for `log(Principal Balance)` as negative when it should be positive. This should be corrected in the documentation, and the model implementation team should make sure that the production model is correctly parameterized.

2. [Consider Lag Effects](#sec-conceptual-soundness):
    + **Category**: Model Development
    + **Rating**: **Moderate**
    + **Recommendation**: Evaluate lag transformations of macroeconomic independent variables, as there may be a time delay between macroeconomic downturns and their impact on default rates.

3. [Evaluate Class Imbalance and Overfitting Risk](#sec-conceptual-soundness)
    + **Category**: Model Development
    + **Rating**: **Moderate**
    + **Recommendation**: Given the few number of default events in the model training data, evaluate the risk of the probability of default model being overfit and, if necessary, employ one of the [recommended remediation strategies](#sec-dependent-variable).

{{< pagebreak >}}

### A Note on Reproducibility

A unique aspect of Ketchbrook's model validation practice is that all validation work is performed in code scripts backed by a version-controlled repository (i.e., folder). This means that any narrative text, tables, figures, equations, slides, etc. contained in this validation report will be *fully reproducible* days, months, or years from now. Further, one can trace the lineage of the results in the report directly to the source data and applied logic. @fig-reproducibility-flow describes this workflow.

```{mermaid}
%%| label: fig-reproducibility-flow
%%| fig-cap: Reproducible Validation Workflow
%%| fig-align: center
%%| fig-pos: H

flowchart LR
A[(Source Data)] --> B(["Logic (Code)"]) --> C[["Results (PDF Report)"]]
```

::: {.callout-tip}
## Why Is Reproducibility Important?

In short, *"Reproducibility = Transparency"*. To the uninitiated, the need for reproducibility may not be entirely clear. However, especially in a validation setting, the *inability* to reproduce the results of the validator would be catastrophic to the integrity of the validation report and opinions therein. As a model validation vendor, Ketchbrook Analytics is committed to providing a deliverable whose results can be identically reproduced not just days or weeks, but years and decades later. This is a focus of our organizational strategy that differentiates us from most vendors in this space.
:::

For example, the RFP response document you are currently reading was authored with two open source pieces of software, [Quarto](https://quarto.org/) and [R](https://www.r-project.org/), and is rendered *programmatically*. The script to render this document is contained in a version-controlled repository, and this document itself is a fully reproducible piece of software that anyone else with access to the repository can run and subsequently produce the *exact* same document as the one you are reading.

Lastly, the use of the {targets} R package [@landau2021] serves as the orchestration pipeline for all of the artifacts created within this report.